version: '3.4'

services:
  flightsapp:
    image: flightsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
  db:
    image: postgis/postgis:15-3.4